default_language_version:
  python: python3.8.3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
  - repo: https://github.com/timothycrosley/isort
    rev: 5.0.9
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear, flake8-comprehensions]
  - repo: https://github.com/prettier/prettier
    rev: 1.18.2
    hooks:
      - id: prettier
        args: [--prose-wrap=always, --print-width=88]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.740
    hooks:
      - id: mypy
